//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilkySouls3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilkySouls3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,00061D3C,Dark Arrow,99,600,0,0
        ///0,00061C10,Feather Arrow,99,600,0,0
        ///0,00061AE4,Fire Arrow,99,600,0,0
        ///0,00061BAC,Large Arrow,99,600,0,0
        ///0,00061C74,Moonlight Arrow,99,600,0,0
        ///0,00061B48,Poison Arrow,99,600,0,0
        ///0,00061A80,Standard Arrow,99,600,0,0
        ///0,00061CD8,Wood Arrow,99,600,0,0
        ///0,00062250,Dragonslayer Greatarrow,50,600,0,0
        ///0,00062318,Dragonslayer Lightning Arrow,50,600,0,0
        ///1,000623E0,Millwood Greatarrow,30,600,0,0
        ///0,0006237C,Onislayer Greatarrow,30,600,0,0
        ///0,00062C78,Exploding Bolt,30,600,0,0
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///ba ef be ad de          mov    edx,0xdeadbeef
        ///45 31 c0                xor    r8d,r8d
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string ApplySpEffect {
            get {
                return ResourceManager.GetString("ApplySpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,14C4B7E8,Alva Armor,1,1,0,0
        ///0,14C4BBD0,Alva Gauntlets,1,1,0,0
        ///0,14C4B400,Alva Helm,1,1,0,0
        ///0,14C4BFB8,Alva Leggings,1,1,0,0
        ///2,15D76068,Antiquated Dress,1,1,0,0
        ///2,15D76450,Antiquated Gloves,1,1,0,0
        ///2,11B2E408,Antiquated Plain Garb,1,1,0,0
        ///2,15D76838,Antiquated Skirt,1,1,0,0
        ///0,13EF1868,Archdeacon Holy Garb,1,1,0,0
        ///0,13EF2038,Archdeacon Skirt,1,1,0,0
        ///0,13EF1480,Archdeacon White Crown,1,1,0,0
        ///0,129F6300,Aristocrat&apos;s Mask,1,1,0,0
        ///0,15B8DBE8,Armor of Thorns,1,1,0,0
        ///0,152F87A8,Armor of the Sun,1,1,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 bb 00 00 00 00 00    movabs rbx,0x0
        ///00 00 00 
        ///48 bf 00 00 00 00 00    movabs rdi,0x0
        ///00 00 00 
        ///4c 8d 2d 00 00 00 00    lea    r13,[rip+0x0]        # 1f &lt;_main+0x1f&gt;
        ///31 f6                   xor    esi,esi
        ///
        ///000000000021 &lt;loop_start&gt;:
        ///3b 35 00 00 00 00       cmp    esi,DWORD PTR [rip+0x0]        # 27 &lt;loop_start+0x6&gt;
        ///73 1b                   jae    44 &lt;loop_end&gt;
        ///48 89 d9                mov    rcx,rbx
        ///41 8b 54 b5 00          mov    edx,DWORD PTR [r13+rsi*4+0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BatchSetEvent {
            get {
                return ResourceManager.GetString("BatchSetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,671088640,4001951
        ///0,503316480,3001950
        ///0,503382016,3011950
        ///0,570490880,3411951
        ///0,520093696,3101954
        ///0,553648128,3301956
        ///0,587202560,3501953
        ///0,637534208,3801956
        ///0,620756992,3701957
        ///0,654311424,3901950
        ///0,536870912,3201950
        ///0,687865856,4101950
        ///1,754974720,4501951
        ///2,838860800,5001951
        ///2,855638016,5101952
        ///2,855703552,5111951.
        /// </summary>
        internal static string BonfiresByBlockId {
            get {
                return ResourceManager.GetString("BonfiresByBlockId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba ef be ad de          mov    edx,0xdeadbeef
        ///41 b8 00 00 00 00       mov    r8d,0x0
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string BonfireWarp {
            get {
                return ResourceManager.GetString("BonfireWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 bf 00 00 00 00 00    movabs rdi,0x0
        ///00 00 00
        ///000000000000000a &lt;start&gt;:
        ///48 63 cb                movsxd rcx,ebx
        ///48 69 c9 88 02 04 00    imul   rcx,rcx,0x40288
        ///48 03 4f 28             add    rcx,QWORD PTR [rdi+0x28]
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///ff c3                   inc    ebx
        ///3b 5f 20                cmp    ebx,DWORD PTR [rdi+0x20]
        ///7c d7                   jl    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BreakAllObjects {
            get {
                return ResourceManager.GetString("BreakAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 bb 00 00 00 00 00    movabs rbx,0x0
        ///00 00 00 
        ///48 89 d9                mov    rcx,rbx
        ///48 81 c1 b0 02 00 00    add    rcx,0x2b0
        ///ba ef be ad de          mov    edx,0xdeadbeef
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///83 f8 10                cmp    eax,0x10
        ///74 28                   je     56 &lt;exit&gt;
        ///48 63 f0                movsxd rsi,eax
        ///8b 94 b3 4c 02 00 00    mov    edx,DWORD PTR [rbx+rsi*4+0x24c]
        ///83 fa ff          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BreakWeapon {
            get {
                return ResourceManager.GetString("BreakWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51                      push   rcx
        ///48 8b 49 08             mov    rcx,QWORD PTR [rcx+0x8]
        ///48 8b 09                mov    rcx,QWORD PTR [rcx]
        ///81 79 28 20 b3 04 00    cmp    DWORD PTR [rcx+0x28],0x4b320
        ///74 0b                   je     1c &lt;handle_left&gt;
        ///81 79 28 21 b3 04 00    cmp    DWORD PTR [rcx+0x28],0x4b321
        ///74 17                   je     31 &lt;handle_right&gt;
        ///eb 28                   jmp    44 &lt;exit&gt;
        ///00000000001c &lt;handle_left&gt;:
        ///48 31 c9                xor    rcx,rcx
        ///3b 0d 00 00 00 00       cmp    ecx,D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ButterflyRng {
            get {
                return ResourceManager.GetString("ButterflyRng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///b8 00 00 c0 bf          mov    eax,0xbfc00000
        ///66 0f 6e c0             movd   xmm0,eax
        ///58                      pop    rax
        ///f3 0f 11 86 fc 01 00    movss  DWORD PTR [rsi+0x1fc],xmm0
        ///00
        ///e9 00 00 00 00          jmp    18 &lt;_main+0x18&gt;.
        /// </summary>
        internal static string CamVertUp {
            get {
                return ResourceManager.GetString("CamVertUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 8d 4c 24 30          lea    rcx,[rsp+0x30]
        ///c7 01 ef be ad de       mov    DWORD PTR [rcx],0xdeadbeef
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///48 89 01                mov    QWORD PTR [rcx],rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string ChrInsByEventId {
            get {
                return ResourceManager.GetString("ChrInsByEventId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///66 0f 7e d8             movd   eax,xmm3
        ///3d 00 40 9c 46          cmp    eax,0x469c4000
        ///74 25                   je     31 &lt;ret&gt;
        ///3d 00 42 9c 46          cmp    eax,0x469c4200
        ///74 1e                   je     31 &lt;ret&gt;
        ///3d 00 44 9c 46          cmp    eax,0x469c4400
        ///74 17                   je     31 &lt;ret&gt;
        ///3d 00 48 9c 46          cmp    eax,0x469c4800
        ///74 10                   je     31 &lt;ret&gt;
        ///58                      pop    rax
        ///48 8b c4                mov    rax,rsp
        ///48 81 e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CinderPhaseLock {
            get {
                return ResourceManager.GetString("CinderPhaseLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 44 24 40 00          mov    BYTE PTR [rsp+0x40],0x0
        ///81 38 59 2f 00 00       cmp    DWORD PTR [rax],0x2f59
        ///0f 84 00 00 00 00       je     11 &lt;_main+0x11&gt;
        ///e9 00 00 00 00          jmp    16 &lt;_main+0x16&gt;.
        /// </summary>
        internal static string CinderSoulmassRemoval {
            get {
                return ResourceManager.GetString("CinderSoulmassRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40000126,Alluring Skull,10,600,0,0
        ///0,400001CD,Black Bug Pellet,5,600,0,0
        ///0,40000129,Black Firebomb,10,600,0,0
        ///0,4000010E,Bloodred Moss Clump,99,600,0,0
        ///0,40000110,Blooming Purple Moss Clump,99,600,0,0
        ///0,400001CA,Blue Bug Pellet,5,600,0,0
        ///0,40000106,Budding Green Blossom,10,600,0,0
        ///0,4000014F,Carthus Rouge,5,600,0,0
        ///0,40000154,Charcoal Pine Bundle,20,600,0,0
        ///0,4000014A,Charcoal Pine Resin,5,600,0,0
        ///0,4000006F,Cracked Red Eye Orb,99,600,0,0
        ///0,400001EA,Dark Sigil,8,0,0,0
        ///0,400000F0,Divine Blessin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Consumables {
            get {
                return ResourceManager.GetString("Consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 c0                test   rax,rax
        ///74 11                   je     1e &lt;no_update&gt;
        ///48 3b 48 50             cmp    rcx,QWORD PTR [rax+0x50]
        ///75 0b                   jne    1e &lt;no_update&gt;
        ///58                      pop    rax
        ///48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///e9 00 00 00 00          jmp    1e &lt;no_update&gt;
        ///
        ///00000000001e &lt;no_update&gt;:
        ///58                      pop    rax
        ///31 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DisableAllExceptTarget {
            get {
                return ResourceManager.GetString("DisableAllExceptTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 30             sub    rsp,0x30
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 83 c4 30             add    rsp,0x30
        ///c3                      ret.
        /// </summary>
        internal static string DropItem {
            get {
                return ResourceManager.GetString("DropItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 e5                mov    rbp,rsp
        ///48 81 ec 98 05 00 00    sub    rsp,0x598
        ///48 8d 8d e0 fb ff ff    lea    rcx,[rbp-0x420]
        ///ba 00 00 00 00          mov    edx,0x0
        ///e8 00 00 00 00          call   1b &lt;_main+0x1b&gt;
        ///48 8d 8d a0 fb ff ff    lea    rcx,[rbp-0x460]
        ///48 8d 95 e0 fa ff ff    lea    rdx,[rbp-0x520]
        ///48 89 51 10             mov    QWORD PTR [rcx+0x10],rdx
        ///b8 00 00 00 00          mov    eax,0x0
        ///89 41 18                mov    DWORD PTR [rcx+0x18],eax
        ///89 42 04                mov    DWORD PTR [rd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExecuteTalkEvent {
            get {
                return ResourceManager.GetString("ExecuteTalkEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///ba ef be ad de          mov    edx,0xdeadbeef
        ///48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string FindAndRemoveSpEffect {
            get {
                return ResourceManager.GetString("FindAndRemoveSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///45 31 c0                xor    r8d,r8d
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 20             sub    rsp,0x20
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///88 01                   mov    BYTE PTR [rcx],al
        ///c3                      ret.
        /// </summary>
        internal static string GetEvent {
            get {
                return ResourceManager.GetString("GetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b8 01 00 00 00          mov    eax,0x1
        ///c3                      ret.
        /// </summary>
        internal static string ItemLotBase {
            get {
                return ResourceManager.GetString("ItemLotBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 12 &lt;_main+0x12&gt;
        ///75 4a                   jne    5e &lt;skip_qty_adjust&gt;
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///48 8d 53 04             lea    rdx,[rbx+0x4]
        ///e8 00 00 00 00          call   27 &lt;_main+0x27&gt;
        ///89 c7                   mov    edi,eax
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///48 8d 53 04             lea    rd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemSpawn {
            get {
                return ResourceManager.GetString("ItemSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,40002345,Applause,1,1,0,0
        ///0,400000BE,Ashen Estus Flask,1,1,0,0
        ///0,40000845,Basin of Vows,1,1,0,0
        ///0,40002328,Beckon,1,1,0,0
        ///0,40000173,Binoculars,1,600,0,0
        ///2,4000086E,Blood of the Dark Soul,1,1,0,0
        ///0,4000232B,Bow,1,1,0,0
        ///0,40000849,Braille Divine Sunlight Tome,1,1,0,0
        ///0,40000847,Braille Divine Tome of Carim,1,1,0,0
        ///0,40000848,Braille Divine Tome of Lothric,1,1,0,0
        ///0,4000233C,By my sword,1,1,0,0
        ///0,40002341,Call over,1,1,0,0
        ///1,4000086A,Captain&apos;s Ashes,1,1,0,0
        ///0,40000850,Carthus Pyromancy Tome,1,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyItems {
            get {
                return ResourceManager.GetString("KeyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///48 ba 00 00 00 00 00    movabs rdx,0x0
        ///00 00 00
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string LuaDoString {
            get {
                return ResourceManager.GetString("LuaDoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 3d 00 00 00 00 01    cmp    DWORD PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///0f 84 14 02 00 00       je     221 &lt;normal&gt;
        ///48 3b 1d 00 00 00 00    cmp    rbx,QWORD PTR [rip+0x0]        # 14 &lt;_main+0x14&gt;
        ///0f 85 07 02 00 00       jne    221 &lt;normal&gt;
        ///53                      push   rbx
        ///55                      push   rbp
        ///56                      push   rsi
        ///57                      push   rdi
        ///41 54                   push   r12
        ///41 55                   push   r13
        ///41 56                   push   r14
        ///41 57      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoveTarget {
            get {
                return ResourceManager.GetString("MoveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 c0                test   rax,rax
        ///74 21                   je     2e &lt;exit&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 15                   je     2e &lt;exit&gt;
        ///48 8b 80 ef be 00 00    mov    rax,QWORD PTR [rax+0xbeef]
        ///48 85 c0                test   rax,rax
        ///74 09                   je     2e &lt;exit&gt;
        ///48 3b 48 68             cmp    rcx, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_InAirTimer {
            get {
                return ResourceManager.GetString("NoClip_InAirTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 ff 90 f8 00 00 00    call   QWORD PTR [r8+0xf8]
        ///84 c0                   test   al,al
        ///74 28                   je     33 &lt;exit&gt;
        ///49 83 fc 62             cmp    r12,0x62
        ///74 0b                   je     1c &lt;set_down&gt;
        ///49 83 fc 7e             cmp    r12,0x7e
        ///74 13                   je     2a &lt;set_up&gt;
        ///e9 00 00 00 00          jmp    1c &lt;set_down&gt;
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 23 &lt;set_down+0x7&gt;
        ///30 c0                   xor    al,al
        ///e9 00 00 00 00          jmp    2a &lt;set_up&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Keyboard {
            get {
                return ResourceManager.GetString("NoClip_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 83 f9 0b             cmp    r9d,0xb
        ///74 0f                   je     15 &lt;set_down&gt;
        ///41 83 f9 0c             cmp    r9d,0xc
        ///74 11                   je     1d &lt;set_up&gt;
        ///53                      push   rbx
        ///57                      push   rdi
        ///41 54                   push   r12
        ///e9 00 00 00 00          jmp    15 &lt;set_down&gt;
        ///
        ///000000000015 &lt;set_down&gt;:
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # 1c &lt;set_down+0x7&gt;
        ///c3                      ret
        ///
        ///00000000001d &lt;set_up&gt;:
        ///c6 05 00 00 00 00 02    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_Triggers {
            get {
                return ResourceManager.GetString("NoClip_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 c0                test   rax,rax
        ///0f 84 71 01 00 00       je     182 &lt;exit&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 39 43 08             cmp    QWORD PTR [rbx+0x8],rax
        ///0f 85 60 01 00 00       jne    182 &lt;exit&gt;
        ///66 0f 6f b3 80 00 00    movdqa xmm6,XMMWORD PTR [rbx+0x80]
        ///00 
        ///56                      push   rsi
        ///52                      push   rdx
        ///51                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoClip_UpdateCoords {
            get {
                return ResourceManager.GetString("NoClip_UpdateCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 31 c0                xor    rax,rax
        ///48 89 02                mov    QWORD PTR [rdx],rax
        ///49 89 04 24             mov    QWORD PTR [r12],rax
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop
        ///90                      nop.
        /// </summary>
        internal static string NoLogo {
            get {
                return ResourceManager.GetString("NoLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///4c 8d 25 00 00 00 00    lea    r12,[rip+0x0]        # b &lt;_main+0xb&gt;
        ///31 db                   xor    ebx,ebx
        ///
        ///00000000000d &lt;loop_top&gt;:
        ///48 8d 0d 00 00 00 00    lea    rcx,[rip+0x0]        # 14 &lt;loop_top+0x7&gt;
        ///ba c6 9b 04 00          mov    edx,0x49bc6
        ///41 b9 08 00 00 00       mov    r9d,0x8
        ///4d 89 e0                mov    r8,r12
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlacePrismStones {
            get {
                return ResourceManager.GetString("PlacePrismStones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g_GoalTable[GOAL_BlackOldKing_514000_Battle].Activate = function(self, ai, goal)
        ///    local probabilities = {}
        ///    local acts = {}
        ///    local paramTbls = {}
        ///    Common_Clear_Param(probabilities, acts, paramTbls)
        ///    Init_Pseudo_Global(ai, goal)
        ///    ai:SetStringIndexedNumber(&quot;Dist_SideStep&quot;, 3.8)
        ///    ai:SetStringIndexedNumber(&quot;Dist_BackStep&quot;, 7.5)
        ///    if ai:HasSpecialEffectId(TARGET_SELF, 10636) then
        ///        ai:AddObserveSpecialEffectAttribute(TARGET_EVENT, 5027)
        ///    end
        ///    if ai:HasSpecialEffectId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PontiffNoClone {
            get {
                return ResourceManager.GetString("PontiffNoClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to g_GoalTable[GOAL_BlackOldKing_514000_Battle].Activate = function(self, ai, goal)
        ///    local probabilities = {}
        ///    local acts = {}
        ///    local paramTbls = {}
        ///    Common_Clear_Param(probabilities, acts, paramTbls)
        ///    Init_Pseudo_Global(ai, goal)
        ///    ai:SetStringIndexedNumber(&quot;Dist_SideStep&quot;, 3.8)
        ///    ai:SetStringIndexedNumber(&quot;Dist_BackStep&quot;, 7.5)
        ///    if ai:HasSpecialEffectId(TARGET_SELF, 10636) then
        ///        ai:AddObserveSpecialEffectAttribute(TARGET_EVENT, 5027)
        ///    end
        ///    if ai:HasSpecialEffectId [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PontiffVanilla {
            get {
                return ResourceManager.GetString("PontiffVanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 20             sub    rsp,0x20
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 83 c4 20             add    rsp,0x20
        ///c3                      ret.
        /// </summary>
        internal static string RefreshFromStorage {
            get {
                return ResourceManager.GetString("RefreshFromStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00
        ///ba 0a 00 00 00          mov    edx,0xa
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///48 83 ec 28             sub    rsp,0x28
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 bf 00 00 00 00 00    movabs rdi,0x0
        ///00 00 00
        ///000000000000000a &lt;start&gt;:
        ///48 63 cb                movsxd rcx,ebx
        ///48 69 c9 88 02 04 00    imul   rcx,rcx,0x40288
        ///48 03 4f 28             add    rcx,QWORD PTR [rdi+0x28]
        ///48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///ff c3                   inc    ebx
        ///3b 5f 20                cmp    ebx,DWORD PTR [rdi+0x20]
        ///7c d7                   jl    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestoreAllObjects {
            get {
                return ResourceManager.GetString("RestoreAllObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,2000508C,Aldrich&apos;s Ruby,1,1,0,0
        ///0,20005096,Aldrich&apos;s Sapphire,1,1,0,0
        ///0,200050E6,Ashen Estus Ring,1,1,0,0
        ///0,20005032,Baneful Bird Ring,1,1,0,0
        ///0,20004F07,Bellowing Dragoncrest Ring,1,1,0,0
        ///0,20004E85,Bloodbite Ring+1,1,1,0,0
        ///0,20004E84,Bloodbite Ring,1,1,0,0
        ///0,20004ED4,Blue Tearstone Ring,1,1,0,0
        ///0,20005078,Calamity Ring,1,1,0,0
        ///0,200050FA,Carthus Bloodring,1,1,0,0
        ///0,20004FE2,Carthus Milkring,1,1,0,0
        ///1,20005208,Chillbite Ring,1,1,0,0
        ///0,20004E2A,Chloranthy Ring,1,1,0,0
        ///0,20004E2B,Chloranthy Ri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rings {
            get {
                return ResourceManager.GetString("Rings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 05 00 00 00 00    mov    QWORD PTR [rip+0x0],rax        # 7 &lt;_main+0x7&gt;
        ///48 8b 80 90 1f 00 00    mov    rax,QWORD PTR [rax+0x1f90]
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string SaveTargetPtr {
            get {
                return ResourceManager.GetString("SaveTargetPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 b9 00 00 00 00 00    movabs rcx,0x0
        ///00 00 00 
        ///ba ef be ad de          mov    edx,0xdeadbeef
        ///41 b8 01 00 00 00       mov    r8d,0x1
        ///41 b9 00 00 00 00       mov    r9d,0x0
        ///48 83 ec 48             sub    rsp,0x48
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///ff d0                   call   rax
        ///48 83 c4 48             add    rsp,0x48
        ///c3                      ret.
        /// </summary>
        internal static string SetEvent {
            get {
                return ResourceManager.GetString("SetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,401875B8,Affinity,1,99,0,0
        ///0,4014B0E0,Aural Decoy,1,99,0,0
        ///0,40149970,Cast Light,1,99,0,0
        ///0,4014ACF8,Chameleon,1,99,0,0
        ///0,4014F348,Crystal Hail,1,99,0,0
        ///0,40140500,Crystal Magic Weapon,1,99,0,0
        ///0,4013F178,Crystal Soul Spear,1,99,0,0
        ///0,40189CC8,Dark Edge,1,99,0,0
        ///0,4013F560,Deep Soul,1,99,0,0
        ///0,40124F80,Farron Dart,1,99,0,0
        ///0,4014FB18,Farron Flashsword,1,99,0,0
        ///0,4014EF60,Farron Hail,1,99,0,0
        ///1,401408E8,Frozen Weapon,1,99,0,0
        ///0,4013F948,Great Deep Soul,1,99,0,0
        ///0,40127690,Great Farron Dart,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spells {
            get {
                return ResourceManager.GetString("Spells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 83 ec 28             sub    rsp,0x28
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00
        ///ff d0                   call   rax
        ///48 83 c4 28             add    rsp,0x28
        ///c3                      ret.
        /// </summary>
        internal static string StopMusic {
            get {
                return ResourceManager.GetString("StopMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8d 8b 28 0b 00 00    lea    rcx,[rbx+0xb28]
        ///48 8d 15 00 00 00 00    lea    rdx,[rip+0x0]        # e &lt;_main+0xe&gt;
        ///e9 00 00 00 00          jmp    13 &lt;_main+0x13&gt;.
        /// </summary>
        internal static string TrySetReminder {
            get {
                return ResourceManager.GetString("TrySetReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,400003E8,Titanite Shard,99,600,0,0
        ///0,400003E9,Large Titanite Shard,99,600,0,0
        ///0,400003EA,Titanite Chunk,99,600,0,0
        ///0,400003EB,Titanite Slab,99,600,0,0
        ///0,400003FC,Titanite Scale,99,600,0,0
        ///0,40000406,Twinkling Titanite,99,600,0,0
        ///0,4000044C,Heavy Gem,99,600,0,0
        ///0,40000456,Sharp Gem,99,600,0,0
        ///0,40000460,Refined Gem,99,600,0,0
        ///0,4000046A,Crystal Gem,99,600,0,0
        ///0,40000474,Simple Gem,99,600,0,0
        ///0,4000047E,Fire Gem,99,600,0,0
        ///0,40000488,Chaos Gem,99,600,0,0
        ///0,40000492,Lightning Gem,99,600,0,0
        ///0,4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpgradeMaterials {
            get {
                return ResourceManager.GetString("UpgradeMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 0f 28 3d 00 00 00    movaps xmm15,XMMWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///00 
        ///44 0f 11 b8 50 0a 00    movups XMMWORD PTR [rax+0xa50],xmm15
        ///00 
        ///45 0f 57 ff             xorps  xmm15,xmm15
        ///e9 00 00 00 00          jmp    19 &lt;_main+0x19&gt;.
        /// </summary>
        internal static string WarpAngleWrite {
            get {
                return ResourceManager.GetString("WarpAngleWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 0f 28 3d 00 00 00    movaps xmm15,XMMWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///00
        ///44 0f 11 b8 40 0a 00    movups XMMWORD PTR [rax+0xa40],xmm15
        ///00
        ///45 0f 57 ff             xorps  xmm15,xmm15
        ///e9 00 00 00 00          jmp    19 &lt;_main+0x19&gt;.
        /// </summary>
        internal static string WarpCoordsWrite {
            get {
                return ResourceManager.GetString("WarpCoordsWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,Boss,Iudex Gundyr,,,4001952,123.96|-63.95|554.54,-2.71
        ///0,Boss,Champion Gundyr,,,4001953,124.44|-63.98|554.00,-2.95
        ///0,Boss,Vordt,,,3001955,27.61|-25.49|51.48,-0.01
        ///0,Boss,Dancer,,,3001955,27.54|-8.58|126.75,3.14
        ///0,Boss,Oceiros,,,3001954,-73.99|-49.43|360.94,2.89
        ///0,Boss,Greatwood,,,3101953,134.07|-180.74|-874.74,-0.31
        ///0,Boss,Crystal Sage,,,3301957,-156.24|-249.25|-424.70,1.84
        ///0,Boss,Abyss Watchers,,,3301958,272.16|-248.78|-485.06,-1.50
        ///0,Boss,Deacons,,,3501950,-449.63|-196.57|-617.35,1.09
        ///0,Boss,Hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WarpEntries {
            get {
                return ResourceManager.GetString("WarpEntries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the Boss Revives dataset (Area,BossName,BlockId,FirstEncounterFlags,BossFlags,BonfireId,Coords,Angle per row).
        /// </summary>
        internal static string BossRevives {
            get {
                return ResourceManager.GetString("BossRevives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,013599D0,Ancient Dragon Greatshield,1,1,2,0
        ///0,002206F0,Anri&apos;s Straight Sword,1,1,2,0
        ///2,116520,Aquamarine Dagger,1,1,2,0
        ///0,00D662D0,Arbalest,1,1,1,0
        ///0,00C80AF0,Archdeacon&apos;s Great Staff,1,1,2,0
        ///0,008BEC50,Arstor&apos;s Spear,1,1,2,0
        ///0,005C9EF0,Astora Greatsword,1,1,1,1
        ///0,002191C0,Astora Straight Sword,1,1,1,1
        ///0,00D6FF10,Avelyn,1,1,1,0
        ///0,000F6950,Bandit&apos;s Knife,1,1,1,1
        ///0,0021B8D0,Barbed Straight Sword,1,1,1,1
        ///0,005B8D80,Bastard Sword,1,1,1,1
        ///0,006AF6D0,Battle Axe,1,1,1,1
        ///0,004CC070,Black Blade,1,1,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
    }
}
